### ISSUE TITLE
[CI/CD] Github Action connect for Deploy - Backend

### ISSUE THREAD

**Issue by cokia** [dimigoin/dimigoin-back-v2#21]
교내서버 접근권한 생기면 작업 시작하겠습니다.

**Comment by uhmseohun** [comment]
카톡방에 계정 공유했습니다 !

**Comment by cokia** [comment]
github action이 여러 self-hosted 러너에 대해서 엑션별로 선택을 할려면 아키텍쳐별로 선택을 해야되서 지금같이 둘다 ubuntu x64를 쓰는 환경에서는 선택이 불가능해 프로덕션과 빌드테스트를 구분할 수 가 없습니다. 그래서 모든 커밋과 머지에 대해서  제 빌드테스트 서버에서 처리를 하고, 
프로덕션의 경우 빌드테스트 서버에서 특정 스크립트 실행(파이썬, 프로덕션서버와 ssh 연결해 배포)으로 프로덕션 배포를 할려고 합니다 괜찮을까요? 

20년 3월 31일까지 깃허브에서 레이블로 러너 선택하는 기능을 배포한다고 하니 그 전까지만 저렇게 설정하면 될거같아요 :)

**Comment by uhmseohun** [comment]
> github action이 여러 self-hosted 러너에 대해서 엑션별로 선택을 할려면 아키텍쳐별로 선택을 해야되서 지금같이 둘다 ubuntu x64를 쓰는 환경에서는 선택이 불가능해 프로덕션과 빌드테스트를 구분할 수 가 없습니다. 그래서 모든 커밋과 머지에 대해서 제 빌드테스트 서버에서 처리를 하고,

그것도 좋을 것 같네요 :)
근데 굳이 설정을 두 번 하는 것보단 우선 배포만 구현을 하고 3월 31일에 빌드 테스트를 설정해도 괜찮을 것 같기도 한데 어떻게 생각하세요?

**Comment by cokia** [comment]
> > github action이 여러 self-hosted 러너에 대해서 엑션별로 선택을 할려면 아키텍쳐별로 선택을 해야되서 지금같이 둘다 ubuntu x64를 쓰는 환경에서는 선택이 불가능해 프로덕션과 빌드테스트를 구분할 수 가 없습니다. 그래서 모든 커밋과 머지에 대해서 제 빌드테스트 서버에서 처리를 하고,
> 
> 그것도 좋을 것 같네요 :)
> 근데 굳이 설정을 두 번 하는 것보단 우선 배포만 구현을 하고 3월 31일에 빌드 테스트를 설정해도 괜찮을 것 같기도 한데 어떻게 생각하세요?

앗 그렇게 되면 저야 좋죠 :) 그럼 그렇게 진행해두겠습니다 ~~

**Comment by uhmseohun** [comment]
> > > github action이 여러 self-hosted 러너에 대해서 엑션별로 선택을 할려면 아키텍쳐별로 선택을 해야되서 지금같이 둘다 ubuntu x64를 쓰는 환경에서는 선택이 불가능해 프로덕션과 빌드테스트를 구분할 수 가 없습니다. 그래서 모든 커밋과 머지에 대해서 제 빌드테스트 서버에서 처리를 하고,
> > 
> > 
> > 그것도 좋을 것 같네요 :)
> > 근데 굳이 설정을 두 번 하는 것보단 우선 배포만 구현을 하고 3월 31일에 빌드 테스트를 설정해도 괜찮을 것 같기도 한데 어떻게 생각하세요?
> 
> 앗 그렇게 되면 저야 좋죠 :) 그럼 그렇게 진행해두겠습니다 ~~

넴넴 감사합니다😊

**Comment by MinSeungHyun** [comment]
깃허브 서버 안쓰고 개인 서버로 하려는 이유가 있나요? @cokia

**Comment by cokia** [comment]
몇가지 이유가 있었습니다

1. 깃허브에서 디폴트로 제공하는 서버는 너무 느립니다.
2. 깃허브에서 제공하는 서버에서는 6 시간 이상 작업을 돌릴수가없습니다 (배포목적으로 부적절)
3. 매번 도메인을 연결 할 수 없기때문에 개발목적의 "임시" 배포로도 부적절하다고 판단했습니다 :)
